In [17]:
import numpy as np

In [18]:
def ex1():
    x = np.arange(21)
    x[9:16] *= -1
    return x

In [19]:
ex1()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [20]:
def ex2():
    x = np.random.randint(0,10,size=5)
    return x

In [21]:
ex2()

array([7, 5, 3, 9, 0])

In [22]:
def ex3(x,y):
    z = x*y
    return z

In [23]:
x = np.arange(21)
y = np.arange(21)
ex3(x,y)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [24]:
def ex4():
    mat = np.arange(10, 22).reshape(3, 4)
    return mat

In [25]:
def ex5(mat):
    x,y =mat.shape
    print('rows = ',x)
    print('columns = ',y)

In [26]:
ex4()

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [27]:
ex5(ex4())

rows =  3
columns =  4


In [28]:
def ex6():
    mat = np.x = np.random.randint(0,2,size=16).reshape(4,4)
    for i in range (4) :
        mat[i,i]=0
    return mat

In [29]:
ex6()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [1, 1, 0, 0]])

In [30]:
def ex7(x,y):
    z = np.intersect1d(x,y)
    return z

In [31]:
x = np.array([0,10,20])
y = np.array([10,40,0])
ex7(x,y)

array([ 0, 10])

In [32]:
def ex8(x):
    x = np.unique(x)
    return x

In [33]:
y = np.array([10,40,0,10,10,0])
ex8(y)

array([ 0, 10, 40])

In [34]:
def ex9(x,y):
    z = np.cross(x,y)
    return z

In [35]:
x = np.array([0,10,20])
y = np.array([10,40,0])
ex9(x,y)

array([-800,  200, -100])

In [36]:
def ex10():
    car = np.random.rand(10,2)
    x = car[:,0]
    y = car[:,1]
    
    r = np.sqrt(x**2+y**2)
    t = np.arctan(y,x)
    pol = np.array([r,t])
    return pol

In [37]:
ex10()

array([[1.08733869, 0.50490014, 0.40453031, 1.08851923, 0.82197565,
        0.52010773, 0.82173113, 0.78214774, 0.94777995, 0.36003724],
       [0.47170715, 0.3302118 , 0.02137866, 0.53798812, 0.15712104,
        0.42388212, 0.21327799, 0.48455605, 0.39981268, 0.26695796]])

In [38]:
def ex11(k):
    x = np.arange(101)
    index=np.argmin(abs(x-k))
    
    return x[index]

In [39]:
ex11(34.51)

35

In [40]:
def ex12():
    x = np.arange(15,56)
    print(x[1:55])

In [41]:
ex12()

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [72]:
def ex13():
    mat = np.random.randint(0,10,size=12).reshape(3,4)
    for i in range(3):
        for j in range(4):
            print(mat[i,j])

In [73]:
ex13()

4
2
8
3
9
1
9
1
9
8
8
2


###### def ex14():
    x = np.linspace(5,50,10)
    return x
